name: flutter_sample_fire
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cloud_firestore: ^3.4.6
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.19.2

flutter:
  uses-material-design: true
