// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsbVv2NZBfNREaP5mhKqlQNtiZO3fJyj8',
    appId: '1:457689841576:web:3aa7ca192e8a2390ee279d',
    messagingSenderId: '457689841576',
    projectId: 'flutter-sample-fire-dev',
    authDomain: 'flutter-sample-fire-dev.firebaseapp.com',
    storageBucket: 'flutter-sample-fire-dev.appspot.com',
    measurementId: 'G-QL9KR6DQZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpg2GgaFQvJMHt76hEPA7ffTI6lNJKUN4',
    appId: '1:457689841576:android:0bed534824a6b01eee279d',
    messagingSenderId: '457689841576',
    projectId: 'flutter-sample-fire-dev',
    storageBucket: 'flutter-sample-fire-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0A85C69-_J7rZeyN2Z9avmE07oDKy7b4',
    appId: '1:457689841576:ios:d92e44a1b16d7217ee279d',
    messagingSenderId: '457689841576',
    projectId: 'flutter-sample-fire-dev',
    storageBucket: 'flutter-sample-fire-dev.appspot.com',
    iosClientId: '457689841576-4rj3pu2j926sqrgqsq7c3n76qkhur5jl.apps.googleusercontent.com',
    iosBundleId: 'jp.keyber.flutterSampleFire',
  );
}
